# Generated by Django 5.0.1 on 2024-01-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prof_user',
            new_name='user',
        ),
    ]
