# Generated by Django 5.0.1 on 2024-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_prof_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Nil', max_length=200),
        ),
    ]
