# Generated by Django 5.0.1 on 2024-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post_draft_alter_post_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_calendar_credentials',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
