# Generated by Django 5.0.1 on 2024-01-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_google_calendar_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_calendar_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
